# Form implementation generated from reading ui file 'ui_files/add_task_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(495, 505)
        icon = QtGui.QIcon.fromTheme("address-book-new")
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.remove_worker_button = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_worker_button.sizePolicy().hasHeightForWidth())
        self.remove_worker_button.setSizePolicy(sizePolicy)
        self.remove_worker_button.setObjectName("remove_worker_button")
        self.gridLayout.addWidget(self.remove_worker_button, 4, 4, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 5, 1, 1)
        self.text_task = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.text_task.setObjectName("text_task")
        self.gridLayout.addWidget(self.text_task, 2, 0, 1, 6)
        self.worker_combobox = QtWidgets.QComboBox(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.worker_combobox.sizePolicy().hasHeightForWidth())
        self.worker_combobox.setSizePolicy(sizePolicy)
        self.worker_combobox.setMinimumSize(QtCore.QSize(50, 0))
        self.worker_combobox.setMaxVisibleItems(7)
        self.worker_combobox.setObjectName("worker_combobox")
        self.gridLayout.addWidget(self.worker_combobox, 5, 0, 1, 1)
        self.routine_checkbox = QtWidgets.QCheckBox(parent=Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.routine_checkbox.setFont(font)
        self.routine_checkbox.setObjectName("routine_checkbox")
        self.gridLayout.addWidget(self.routine_checkbox, 5, 5, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.add_worker_button = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_worker_button.sizePolicy().hasHeightForWidth())
        self.add_worker_button.setSizePolicy(sizePolicy)
        self.add_worker_button.setObjectName("add_worker_button")
        self.gridLayout.addWidget(self.add_worker_button, 5, 4, 1, 1)
        self.workers_label = QtWidgets.QLabel(parent=Dialog)
        self.workers_label.setObjectName("workers_label")
        self.gridLayout.addWidget(self.workers_label, 4, 0, 1, 1)
        self.add_photo = QtWidgets.QPushButton(parent=Dialog)
        self.add_photo.setMaximumSize(QtCore.QSize(32, 32))
        self.add_photo.setAutoFillBackground(False)
        self.add_photo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui_files/../Images/add_photo_photo_tool_chatting_social_media_icon_197276.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_photo.setIcon(icon)
        self.add_photo.setIconSize(QtCore.QSize(32, 32))
        self.add_photo.setObjectName("add_photo")
        self.gridLayout.addWidget(self.add_photo, 0, 4, 1, 1)
        self.photo_name = QtWidgets.QLabel(parent=Dialog)
        self.photo_name.setText("")
        self.photo_name.setScaledContents(False)
        self.photo_name.setObjectName("photo_name")
        self.gridLayout.addWidget(self.photo_name, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление задачи"))
        self.remove_worker_button.setText(_translate("Dialog", "-"))
        self.text_task.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\">При нажатии флажка &quot;ТО&quot;, данное поле закрыто для записи. Данные запишутся автоматически</p></body></html>"))
        self.text_task.setPlaceholderText(_translate("Dialog", "Наименование задачи"))
        self.routine_checkbox.setText(_translate("Dialog", "ТО"))
        self.add_worker_button.setText(_translate("Dialog", "+"))
        self.workers_label.setText(_translate("Dialog", "Исполнители"))
        self.add_photo.setToolTip(_translate("Dialog", "<html><head/><body><p>Прикрепить фото</p></body></html>"))
