# Form implementation generated from reading ui file 'add_task_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(580, 423)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(9, 389, 169, 25))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.name_of_task = QtWidgets.QLabel(parent=Dialog)
        self.name_of_task.setGeometry(QtCore.QRect(9, 9, 107, 17))
        self.name_of_task.setObjectName("name_of_task")
        self.text_task = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.text_task.setGeometry(QtCore.QRect(23, 49, 501, 121))
        self.text_task.setObjectName("text_task")
        self.workers_label = QtWidgets.QLabel(parent=Dialog)
        self.workers_label.setGeometry(QtCore.QRect(10, 190, 107, 17))
        self.workers_label.setObjectName("workers_label")
        self.worker_combobox = QtWidgets.QComboBox(parent=Dialog)
        self.worker_combobox.setGeometry(QtCore.QRect(10, 220, 181, 31))
        self.worker_combobox.setObjectName("worker_combobox")
        self.add_worker_button = QtWidgets.QPushButton(parent=Dialog)
        self.add_worker_button.setGeometry(QtCore.QRect(400, 220, 89, 25))
        self.add_worker_button.setObjectName("add_worker_button")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.name_of_task.setText(_translate("Dialog", "Наименование"))
        self.workers_label.setText(_translate("Dialog", "Исполнители"))
        self.add_worker_button.setText(_translate("Dialog", "+"))
