# Form implementation generated from reading ui file 'ui_files/add_task_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(531, 542)
        icon = QtGui.QIcon.fromTheme("address-book-new")
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.workers_label = QtWidgets.QLabel(parent=Dialog)
        self.workers_label.setObjectName("workers_label")
        self.gridLayout.addWidget(self.workers_label, 3, 0, 1, 1)
        self.worker_combobox = QtWidgets.QComboBox(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.worker_combobox.sizePolicy().hasHeightForWidth())
        self.worker_combobox.setSizePolicy(sizePolicy)
        self.worker_combobox.setMinimumSize(QtCore.QSize(50, 0))
        self.worker_combobox.setMaxVisibleItems(7)
        self.worker_combobox.setObjectName("worker_combobox")
        self.gridLayout.addWidget(self.worker_combobox, 4, 0, 1, 1)
        self.text_task = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.text_task.setObjectName("text_task")
        self.gridLayout.addWidget(self.text_task, 1, 0, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 2, 1, 1)
        self.add_worker_button = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_worker_button.sizePolicy().hasHeightForWidth())
        self.add_worker_button.setSizePolicy(sizePolicy)
        self.add_worker_button.setObjectName("add_worker_button")
        self.gridLayout.addWidget(self.add_worker_button, 4, 1, 1, 1)
        self.remove_worker_button = QtWidgets.QPushButton(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_worker_button.sizePolicy().hasHeightForWidth())
        self.remove_worker_button.setSizePolicy(sizePolicy)
        self.remove_worker_button.setObjectName("remove_worker_button")
        self.gridLayout.addWidget(self.remove_worker_button, 4, 2, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 5, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление задачи"))
        self.workers_label.setText(_translate("Dialog", "Исполнители"))
        self.text_task.setPlaceholderText(_translate("Dialog", "Наименование задачи"))
        self.add_worker_button.setText(_translate("Dialog", "+"))
        self.remove_worker_button.setText(_translate("Dialog", "-"))
        self.checkBox.setText(_translate("Dialog", "Регламентное мероприятие"))
