# Form implementation generated from reading ui file 'ui_files/complete_task.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_elimination_task(object):
    def setupUi(self, elimination_task):
        elimination_task.setObjectName("elimination_task")
        elimination_task.resize(583, 544)
        icon = QtGui.QIcon.fromTheme("accessories-text-editor")
        elimination_task.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(elimination_task)
        self.gridLayout.setObjectName("gridLayout")
        self.name_of_task = QtWidgets.QLabel(parent=elimination_task)
        self.name_of_task.setMaximumSize(QtCore.QSize(16777215, 200))
        self.name_of_task.setText("")
        self.name_of_task.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_of_task.setObjectName("name_of_task")
        self.gridLayout.addWidget(self.name_of_task, 1, 1, 1, 2)
        self.operations = QtWidgets.QLabel(parent=elimination_task)
        self.operations.setMaximumSize(QtCore.QSize(16777215, 350))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.operations.setFont(font)
        self.operations.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.operations.setObjectName("operations")
        self.gridLayout.addWidget(self.operations, 2, 0, 1, 1)
        self.indicators_label = QtWidgets.QLabel(parent=elimination_task)
        self.indicators_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.indicators_label.setFont(font)
        self.indicators_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.indicators_label.setObjectName("indicators_label")
        self.gridLayout.addWidget(self.indicators_label, 3, 0, 1, 1)
        self.elimination_task_label = QtWidgets.QLabel(parent=elimination_task)
        self.elimination_task_label.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.elimination_task_label.setFont(font)
        self.elimination_task_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.elimination_task_label.setObjectName("elimination_task_label")
        self.gridLayout.addWidget(self.elimination_task_label, 1, 0, 1, 1)
        self.plus_indicator_combobox = QtWidgets.QPushButton(parent=elimination_task)
        self.plus_indicator_combobox.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.plus_indicator_combobox.setFont(font)
        self.plus_indicator_combobox.setObjectName("plus_indicator_combobox")
        self.gridLayout.addWidget(self.plus_indicator_combobox, 3, 1, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=elimination_task)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 350))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 2, 1, 1, 2)
        self.minus_indicator_combobox = QtWidgets.QPushButton(parent=elimination_task)
        self.minus_indicator_combobox.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.minus_indicator_combobox.setFont(font)
        self.minus_indicator_combobox.setObjectName("minus_indicator_combobox")
        self.gridLayout.addWidget(self.minus_indicator_combobox, 3, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=elimination_task)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 0, 1, 3)

        self.retranslateUi(elimination_task)
        QtCore.QMetaObject.connectSlotsByName(elimination_task)

    def retranslateUi(self, elimination_task):
        _translate = QtCore.QCoreApplication.translate
        elimination_task.setWindowTitle(_translate("elimination_task", "Устранение задачи"))
        self.operations.setText(_translate("elimination_task", "Что было сделано"))
        self.indicators_label.setText(_translate("elimination_task", "Контролируемый показатель"))
        self.elimination_task_label.setText(_translate("elimination_task", "Наименование"))
        self.plus_indicator_combobox.setText(_translate("elimination_task", "+"))
        self.minus_indicator_combobox.setText(_translate("elimination_task", "-"))
