# Form implementation generated from reading ui file 'elimination_task.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_elimination_task(object):
    def setupUi(self, elimination_task):
        elimination_task.setObjectName("elimination_task")
        elimination_task.resize(604, 506)
        icon = QtGui.QIcon.fromTheme("accessories-text-editor")
        elimination_task.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(elimination_task)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=elimination_task)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.elimination_task_label = QtWidgets.QLabel(parent=elimination_task)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.elimination_task_label.setFont(font)
        self.elimination_task_label.setObjectName("elimination_task_label")
        self.gridLayout.addWidget(self.elimination_task_label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=elimination_task)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)

        self.retranslateUi(elimination_task)
        self.buttonBox.accepted.connect(elimination_task.accept) # type: ignore
        self.buttonBox.rejected.connect(elimination_task.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(elimination_task)

    def retranslateUi(self, elimination_task):
        _translate = QtCore.QCoreApplication.translate
        elimination_task.setWindowTitle(_translate("elimination_task", "Устранение задачи"))
        self.elimination_task_label.setText(_translate("elimination_task", "Наименование"))
