from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_form(object):
    def setupUi(self, login_form):
        login_form.setObjectName("login_form")
        login_form.resize(908, 719)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login_form.sizePolicy().hasHeightForWidth())
        login_form.setSizePolicy(sizePolicy)
        login_form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon.fromTheme("applications-engineering")
        login_form.setWindowIcon(icon)
        login_form.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(login_form)
        self.gridLayout.setContentsMargins(50, 100, 50, 50)
        self.gridLayout.setObjectName("gridLayout")
        self.label_login = QtWidgets.QLabel(parent=login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_login.sizePolicy().hasHeightForWidth())
        self.label_login.setSizePolicy(sizePolicy)
        self.label_login.setObjectName("label_login")
        self.gridLayout.addWidget(self.label_login, 0, 0, 1, 1)
        self.login_text = QtWidgets.QLineEdit(parent=login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_text.sizePolicy().hasHeightForWidth())
        self.login_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.login_text.setFont(font)
        self.login_text.setText("")
        self.login_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.login_text.setObjectName("login_text")
        self.gridLayout.addWidget(self.login_text, 0, 1, 1, 1)
        self.label_passw = QtWidgets.QLabel(parent=login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_passw.sizePolicy().hasHeightForWidth())
        self.label_passw.setSizePolicy(sizePolicy)
        self.label_passw.setObjectName("label_passw")
        self.gridLayout.addWidget(self.label_passw, 1, 0, 1, 1)
        self.password_text = QtWidgets.QLineEdit(parent=login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_text.sizePolicy().hasHeightForWidth())
        self.password_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.password_text.setFont(font)
        self.password_text.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_text.setObjectName("password_text")
        self.gridLayout.addWidget(self.password_text, 1, 1, 1, 1)
        self.btn_login = QtWidgets.QPushButton(parent=login_form)
        self.btn_login.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.gridLayout.addWidget(self.btn_login, 2, 1, 1, 1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        
        self.retranslateUi(login_form)
        QtCore.QMetaObject.connectSlotsByName(login_form)

    def retranslateUi(self, login_form):
        _translate = QtCore.QCoreApplication.translate
        login_form.setWindowTitle(_translate("login_form", "Авторизация"))
        self.label_login.setText(_translate("login_form", "Логин"))
        self.login_text.setWhatsThis(_translate("login_form", "Логин"))
        self.label_passw.setText(_translate("login_form", "Пароль"))
        self.password_text.setWhatsThis(_translate("login_form", "Пароль"))
        self.btn_login.setText(_translate("login_form", "Войти"))
