# Form implementation generated from reading ui file 'ui_files/login_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_form(object):
    def setupUi(self, login_form):
        login_form.setObjectName("login_form")
        login_form.resize(908, 719)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login_form.sizePolicy().hasHeightForWidth())
        login_form.setSizePolicy(sizePolicy)
        login_form.setMaximumSize(QtCore.QSize(2079, 720))
        icon = QtGui.QIcon.fromTheme("applications-internet")
        login_form.setWindowIcon(icon)
        login_form.setAutoFillBackground(False)
        self.gridLayout = QtWidgets.QGridLayout(login_form)
        self.gridLayout.setContentsMargins(50, 100, 50, 50)
        self.gridLayout.setObjectName("gridLayout")
        self.login_text = QtWidgets.QLineEdit(parent=login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_text.sizePolicy().hasHeightForWidth())
        self.login_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.login_text.setFont(font)
        self.login_text.setText("")
        self.login_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.login_text.setObjectName("login_text")
        self.gridLayout.addWidget(self.login_text, 0, 0, 1, 1)
        self.password_text = QtWidgets.QLineEdit(parent=login_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_text.sizePolicy().hasHeightForWidth())
        self.password_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.password_text.setFont(font)
        self.password_text.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.password_text.setObjectName("password_text")
        self.gridLayout.addWidget(self.password_text, 1, 0, 1, 1)
        self.btn_login = QtWidgets.QPushButton(parent=login_form)
        self.btn_login.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(True)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.gridLayout.addWidget(self.btn_login, 2, 0, 1, 1)
        self.evp_img = QtWidgets.QLabel(parent=login_form)
        self.evp_img.setMaximumSize(QtCore.QSize(1500, 250))
        self.evp_img.setText("")
        self.evp_img.setPixmap(QtGui.QPixmap("ui_files/../Images/Logo_without_font.png"))
        self.evp_img.setScaledContents(False)
        self.evp_img.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.evp_img.setObjectName("evp_img")
        self.gridLayout.addWidget(self.evp_img, 3, 0, 1, 1)

        self.retranslateUi(login_form)
        QtCore.QMetaObject.connectSlotsByName(login_form)

    def retranslateUi(self, login_form):
        _translate = QtCore.QCoreApplication.translate
        login_form.setWindowTitle(_translate("login_form", "Авторизация"))
        self.login_text.setWhatsThis(_translate("login_form", "Логин"))
        self.login_text.setPlaceholderText(_translate("login_form", "Логин"))
        self.password_text.setWhatsThis(_translate("login_form", "Пароль"))
        self.password_text.setPlaceholderText(_translate("login_form", "Пароль"))
        self.btn_login.setText(_translate("login_form", "Войти"))
