# Form implementation generated from reading ui file 'ui_files/operations_table_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_operations_table_widget(object):
    def setupUi(self, operations_table_widget):
        operations_table_widget.setObjectName("operations_table_widget")
        operations_table_widget.resize(445, 429)
        icon = QtGui.QIcon.fromTheme("applications-engineering")
        operations_table_widget.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(operations_table_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=operations_table_widget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 0, 1, 8)
        self.line = QtWidgets.QFrame(parent=operations_table_widget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 8)
        self.allin_checkbox = QtWidgets.QCheckBox(parent=operations_table_widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.allin_checkbox.setFont(font)
        self.allin_checkbox.setObjectName("allin_checkbox")
        self.gridLayout.addWidget(self.allin_checkbox, 2, 0, 1, 1)
        self.operation_table = QtWidgets.QTableWidget(parent=operations_table_widget)
        self.operation_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.operation_table.setColumnCount(2)
        self.operation_table.setObjectName("operation_table")
        self.operation_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.operation_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.operation_table.setHorizontalHeaderItem(1, item)
        self.operation_table.horizontalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.operation_table, 1, 0, 1, 8)
        self.add_indicator_label = QtWidgets.QLabel(parent=operations_table_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        self.add_indicator_label.setFont(font)
        self.add_indicator_label.setObjectName("add_indicator_label")
        self.gridLayout.addWidget(self.add_indicator_label, 4, 0, 1, 6)
        self.minus_button = QtWidgets.QPushButton(parent=operations_table_widget)
        self.minus_button.setMaximumSize(QtCore.QSize(70, 16777215))
        self.minus_button.setObjectName("minus_button")
        self.gridLayout.addWidget(self.minus_button, 4, 7, 1, 1)
        self.plus_button = QtWidgets.QPushButton(parent=operations_table_widget)
        self.plus_button.setMaximumSize(QtCore.QSize(70, 16777215))
        self.plus_button.setObjectName("plus_button")
        self.gridLayout.addWidget(self.plus_button, 4, 6, 1, 1)

        self.retranslateUi(operations_table_widget)
        QtCore.QMetaObject.connectSlotsByName(operations_table_widget)

    def retranslateUi(self, operations_table_widget):
        _translate = QtCore.QCoreApplication.translate
        operations_table_widget.setWindowTitle(_translate("operations_table_widget", "Выполнение ТО"))
        self.allin_checkbox.setText(_translate("operations_table_widget", "Выполнить всё"))
        item = self.operation_table.horizontalHeaderItem(0)
        item.setText(_translate("operations_table_widget", "Наименование"))
        item = self.operation_table.horizontalHeaderItem(1)
        item.setText(_translate("operations_table_widget", "Статус"))
        self.add_indicator_label.setText(_translate("operations_table_widget", "Контролируемые показатели"))
        self.minus_button.setText(_translate("operations_table_widget", "-"))
        self.plus_button.setText(_translate("operations_table_widget", "+"))
