# Form implementation generated from reading ui file 'ui_files/socket_status.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_socket_status(object):
    def setupUi(self, socket_status):
        socket_status.setObjectName("socket_status")
        socket_status.resize(500, 616)
        socket_status.setMinimumSize(QtCore.QSize(500, 600))
        socket_status.setMaximumSize(QtCore.QSize(800, 1000))
        self.gridLayout = QtWidgets.QGridLayout(socket_status)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_9 = QtWidgets.QPushButton(parent=socket_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMaximumSize(QtCore.QSize(500, 300))
        self.pushButton_9.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: rgb(28, 113, 216);\n"
"    font: 700 italic 16pt \"Ubuntu\";\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 25%;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(parent=socket_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMaximumSize(QtCore.QSize(500, 300))
        self.pushButton_7.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(145, 65, 172);\n"
"    font: 700 italic 16pt \"Ubuntu\";\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 25%;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 4, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=socket_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(500, 300))
        self.pushButton.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.pushButton.setStyleSheet("QPushButton { \n"
"background-color: rgb(0, 207, 33);\n"
"font: 700 italic 16pt \"Ubuntu\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 25%;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid white; \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(parent=socket_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMaximumSize(QtCore.QSize(500, 300))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(160, 167, 27);\n"
"    font: 700 italic 16pt \"Ubuntu\";\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 25%;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=socket_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMaximumSize(QtCore.QSize(500, 300))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 41, 236);\n"
"    font: 700 italic 16pt \"Ubuntu\";\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 25%;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 6, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(parent=socket_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMaximumSize(QtCore.QSize(500, 300))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: rgb(224, 27, 36); \n"
"    font: 700 italic 16pt \"Ubuntu\";\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 25%;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid white;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 0, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(parent=socket_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMaximumSize(QtCore.QSize(500, 300))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(19, 185, 155);\n"
"    font: 700 italic 16pt \"Ubuntu\";\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 25%;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 4, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=socket_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMaximumSize(QtCore.QSize(500, 300))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 50, 135);\n"
"    font: 700 italic 16pt \"Ubuntu\";\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 25%;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 8, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=socket_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(500, 300))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(210, 105, 30);\n"
"    font: 700 italic 16pt \"Ubuntu\";\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 25%;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 8, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(parent=socket_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMaximumSize(QtCore.QSize(500, 300))
        self.pushButton_6.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(181, 131, 90);\n"
"    font: 700 italic 16pt \"Ubuntu\";\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius: 25%;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 2px solid white;\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 6, 1, 1, 1)

        self.retranslateUi(socket_status)
        QtCore.QMetaObject.connectSlotsByName(socket_status)

    def retranslateUi(self, socket_status):
        _translate = QtCore.QCoreApplication.translate
        socket_status.setWindowTitle(_translate("socket_status", "Выберите статус гнезда"))
        self.pushButton_9.setText(_translate("socket_status", "Полосит грязь"))
        self.pushButton_7.setText(_translate("socket_status", "Облой по\n"
"смыканию"))
        self.pushButton.setText(_translate("socket_status", "В работе"))
        self.pushButton_8.setText(_translate("socket_status", "Скол иглы"))
        self.pushButton_4.setText(_translate("socket_status", "Увеличенный\n"
" литник"))
        self.pushButton_10.setText(_translate("socket_status", "Недолив"))
        self.pushButton_5.setText(_translate("socket_status", "Отверстие"))
        self.pushButton_3.setText(_translate("socket_status", "Не греет"))
        self.pushButton_2.setText(_translate("socket_status", "Вода"))
        self.pushButton_6.setText(_translate("socket_status", "Скол трещина"))
