# Form implementation generated from reading ui file 'ui_files/task_info_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_task_info_widget(object):
    def setupUi(self, task_info_widget):
        task_info_widget.setObjectName("task_info_widget")
        task_info_widget.resize(512, 410)
        self.gridLayout = QtWidgets.QGridLayout(task_info_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.name_line_edit = QtWidgets.QLineEdit(parent=task_info_widget)
        self.name_line_edit.setObjectName("name_line_edit")
        self.gridLayout.addWidget(self.name_line_edit, 1, 1, 1, 1)
        self.name_label = QtWidgets.QLabel(parent=task_info_widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=task_info_widget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 0, 1, 2)

        self.retranslateUi(task_info_widget)
        QtCore.QMetaObject.connectSlotsByName(task_info_widget)

    def retranslateUi(self, task_info_widget):
        _translate = QtCore.QCoreApplication.translate
        task_info_widget.setWindowTitle(_translate("task_info_widget", "Подробности задачи"))
        self.name_label.setText(_translate("task_info_widget", "Наименование"))
