# Form implementation generated from reading ui file 'ui_files/what_has_been_done_to_eliminate.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_what_eliminated(object):
    def setupUi(self, what_eliminated):
        what_eliminated.setObjectName("what_eliminated")
        what_eliminated.resize(608, 484)
        self.gridLayout = QtWidgets.QGridLayout(what_eliminated)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=what_eliminated)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 0, 1, 1)
        self.label_spare_parts = QtWidgets.QLabel(parent=what_eliminated)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.label_spare_parts.setFont(font)
        self.label_spare_parts.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_spare_parts.setObjectName("label_spare_parts")
        self.gridLayout.addWidget(self.label_spare_parts, 3, 0, 1, 1)
        self.textEdit_what_eliminated = QtWidgets.QTextEdit(parent=what_eliminated)
        self.textEdit_what_eliminated.setStatusTip("")
        self.textEdit_what_eliminated.setObjectName("textEdit_what_eliminated")
        self.gridLayout.addWidget(self.textEdit_what_eliminated, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=what_eliminated)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 1)

        self.retranslateUi(what_eliminated)
        QtCore.QMetaObject.connectSlotsByName(what_eliminated)

    def retranslateUi(self, what_eliminated):
        _translate = QtCore.QCoreApplication.translate
        what_eliminated.setWindowTitle(_translate("what_eliminated", "Form"))
        self.label_spare_parts.setText(_translate("what_eliminated", "Затраченные запчасти"))
        self.textEdit_what_eliminated.setToolTip(_translate("what_eliminated", "Перечень проделанных операций"))
        self.textEdit_what_eliminated.setPlaceholderText(_translate("what_eliminated", "Что было сделано для устранения?"))
