# Form implementation generated from reading ui file 'ui_files/what_has_been_done_to_eliminate.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_what_eliminated(object):
    def setupUi(self, what_eliminated):
        what_eliminated.setObjectName("what_eliminated")
        what_eliminated.resize(594, 562)
        self.gridLayout = QtWidgets.QGridLayout(what_eliminated)
        self.gridLayout.setObjectName("gridLayout")
        self.plus_button = QtWidgets.QPushButton(parent=what_eliminated)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plus_button.sizePolicy().hasHeightForWidth())
        self.plus_button.setSizePolicy(sizePolicy)
        self.plus_button.setObjectName("plus_button")
        self.gridLayout.addWidget(self.plus_button, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=what_eliminated)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.minus_button = QtWidgets.QPushButton(parent=what_eliminated)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minus_button.sizePolicy().hasHeightForWidth())
        self.minus_button.setSizePolicy(sizePolicy)
        self.minus_button.setObjectName("minus_button")
        self.gridLayout.addWidget(self.minus_button, 2, 1, 1, 1)
        self.plainTextEtextEdit_what_eliminateddit = QtWidgets.QPlainTextEdit(parent=what_eliminated)
        self.plainTextEtextEdit_what_eliminateddit.setObjectName("plainTextEtextEdit_what_eliminateddit")
        self.gridLayout.addWidget(self.plainTextEtextEdit_what_eliminateddit, 1, 0, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=what_eliminated)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 0, 1, 3)

        self.retranslateUi(what_eliminated)
        QtCore.QMetaObject.connectSlotsByName(what_eliminated)

    def retranslateUi(self, what_eliminated):
        _translate = QtCore.QCoreApplication.translate
        what_eliminated.setWindowTitle(_translate("what_eliminated", "Что было сделано?"))
        self.plus_button.setText(_translate("what_eliminated", "+"))
        self.label.setText(_translate("what_eliminated", "Затраченные запчасти"))
        self.minus_button.setText(_translate("what_eliminated", "-"))
        self.plainTextEtextEdit_what_eliminateddit.setPlaceholderText(_translate("what_eliminated", "Что было сделано для устранения?"))
